# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 74f47b5e255791de35d17e133658e817ec19d4c22ef5a76905361280db0d366012f86d33e9386930a9aed4f00337bd3747767f448008ece0a3b95e19daa3baed

test:
  secret_key_base: 9a484d2c919802f01ea33837bef98e1da9e26847021458692ab51cffda4a592447fea1a301c2a3e76be7222f950aad177c038e12ed99987796aacceb1b7a6608

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
